language: java
jdk:
- oraclejdk8
script:
- "./gradlew -Dfile.encoding=UTF-8 clean test buildPlugin"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  # any release is a pre-release that need to be promoted manually
  prerelease: true
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: L7f73+dt2+XCdhLsMDwkG/Y9Y2DIx1zghK+6eG84kEiPn/Dn9Dw7ZPt3Zwst2hCIjvq9mkUOup4s0bVh5IhsPahGseA5I1LCkxdV8Z/gIRvHFtd5jViBpa9iPiyuc9V70tBp77t/0lRnpRX0xQaqIDlFMK1wvoKzSuWu17y6Qwk=
  file: build/distributions/asciidoctor.zip
  on:
    repo: asciidoctor/asciidoctor-intellij-plugin
    all_branches: false
    tags: true
